[INFO     2011-01-03 11:29:35,538 bulkloader.py] Logging to bulkloader-log-20110103.112935
[INFO     2011-01-03 11:29:35,538 bulkloader.py] Throttling transfers:
[INFO     2011-01-03 11:29:35,538 bulkloader.py] Bandwidth: 250000 bytes/second
[INFO     2011-01-03 11:29:35,538 bulkloader.py] HTTP connections: 8/second
[INFO     2011-01-03 11:29:35,539 bulkloader.py] Entities inserted/fetched/modified: 20/second
[INFO     2011-01-03 11:29:35,539 bulkloader.py] Batch Size: 10
[INFO     2011-01-03 11:29:35,539 bulkloader.py] Opening database: bulkloader-progress-20110103.112935.sql3
[DEBUG    2011-01-03 11:29:35,722 bulkloader.py] [Thread-1] RestoreThread: started
[DEBUG    2011-01-03 11:29:35,731 bulkloader.py] [Thread-1] RestoreThread: exiting
[DEBUG    2011-01-03 11:29:35,997 bulkloader.py] [Thread-2] RestoreThread: started
[DEBUG    2011-01-03 11:29:36,006 bulkloader.py] [Thread-2] RestoreThread: exiting
[DEBUG    2011-01-03 11:29:36,006 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,007 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,007 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,007 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,007 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,008 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,008 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,008 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,008 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,009 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: started
[DEBUG    2011-01-03 11:29:36,009 bulkloader.py] Configuring remote_api. url_path = /_ah/remote_api, servername = localhost:8086
[DEBUG    2011-01-03 11:29:39,024 bulkloader.py] Bulkloader using app_id: quote-portfolio
[INFO     2011-01-03 11:29:39,076 bulkloader.py] Connecting to localhost:8086/_ah/remote_api
[DEBUG    2011-01-03 11:29:39,909 bulkloader.py] [Thread-13] ProgressTrackerThread: started
[DEBUG    2011-01-03 11:29:39,909 bulkloader.py] [Thread-14] DataSourceThread: started
[INFO     2011-01-03 11:29:39,909 bulkloader.py] Starting import; maximum 10 entities per post
[DEBUG    2011-01-03 11:29:39,934 adaptive_thread_pool.py] [WorkerThread-0] Got work item [1-10]
[DEBUG    2011-01-03 11:29:40,024 bulkloader.py] [WorkerThread-0] [1-10] Transferred 10 entities in 0.1 seconds
[DEBUG    2011-01-03 11:29:40,024 adaptive_thread_pool.py] Increasing active thread count to 2
[DEBUG    2011-01-03 11:29:40,025 adaptive_thread_pool.py] [WorkerThread-0] Got work item [11-20]
[DEBUG    2011-01-03 11:29:40,025 adaptive_thread_pool.py] [WorkerThread-4] Got work item [21-30]
[DEBUG    2011-01-03 11:29:40,144 bulkloader.py] [WorkerThread-4] [21-30] Transferred 10 entities in 0.1 seconds
[DEBUG    2011-01-03 11:29:40,144 adaptive_thread_pool.py] Increasing active thread count to 3
[DEBUG    2011-01-03 11:29:40,151 adaptive_thread_pool.py] [WorkerThread-4] Got work item [31-40]
[DEBUG    2011-01-03 11:29:40,160 adaptive_thread_pool.py] [WorkerThread-6] Got work item [41-50]
[DEBUG    2011-01-03 11:29:40,219 bulkloader.py] [WorkerThread-0] [11-20] Transferred 10 entities in 0.2 seconds
[DEBUG    2011-01-03 11:29:40,220 adaptive_thread_pool.py] Increasing active thread count to 4
[DEBUG    2011-01-03 11:29:40,220 adaptive_thread_pool.py] [WorkerThread-8] Got work item [51-60]
[DEBUG    2011-01-03 11:29:40,220 adaptive_thread_pool.py] [WorkerThread-9] Got work item [61-70]
[DEBUG    2011-01-03 11:29:40,310 bulkloader.py] [WorkerThread-6] [41-50] Transferred 10 entities in 0.1 seconds
[DEBUG    2011-01-03 11:29:40,311 adaptive_thread_pool.py] Increasing active thread count to 5
[DEBUG    2011-01-03 11:29:40,311 adaptive_thread_pool.py] [WorkerThread-6] Got work item [71-80]
[DEBUG    2011-01-03 11:29:40,311 adaptive_thread_pool.py] [WorkerThread-1] Got work item [81-90]
[DEBUG    2011-01-03 11:29:40,521 bulkloader.py] [Thread-14] DataSourceThread: exiting
[DEBUG    2011-01-03 11:29:40,544 bulkloader.py] Waiting for worker threads to finish...
[DEBUG    2011-01-03 11:29:40,629 bulkloader.py] [WorkerThread-4] [31-40] Transferred 10 entities in 0.5 seconds
[DEBUG    2011-01-03 11:29:40,629 adaptive_thread_pool.py] Increasing active thread count to 6
[DEBUG    2011-01-03 11:29:40,629 adaptive_thread_pool.py] [WorkerThread-4] Got work item [91-100]
[DEBUG    2011-01-03 11:29:40,629 adaptive_thread_pool.py] [WorkerThread-3] Got work item [101-110]
[DEBUG    2011-01-03 11:29:40,705 bulkloader.py] [WorkerThread-8] [51-60] Transferred 10 entities in 0.5 seconds
[DEBUG    2011-01-03 11:29:40,705 adaptive_thread_pool.py] Increasing active thread count to 7
[DEBUG    2011-01-03 11:29:40,705 adaptive_thread_pool.py] [WorkerThread-8] Got work item [111-120]
[DEBUG    2011-01-03 11:29:40,706 adaptive_thread_pool.py] [WorkerThread-7] Got work item [121-130]
[DEBUG    2011-01-03 11:29:40,763 bulkloader.py] [WorkerThread-9] [61-70] Transferred 10 entities in 0.5 seconds
[DEBUG    2011-01-03 11:29:40,763 adaptive_thread_pool.py] Increasing active thread count to 8
[DEBUG    2011-01-03 11:29:40,764 adaptive_thread_pool.py] [WorkerThread-9] Got work item [131-140]
[DEBUG    2011-01-03 11:29:40,764 adaptive_thread_pool.py] [WorkerThread-2] Got work item [141-150]
[DEBUG    2011-01-03 11:29:40,832 bulkloader.py] [WorkerThread-1] [81-90] Transferred 10 entities in 0.5 seconds
[DEBUG    2011-01-03 11:29:40,833 adaptive_thread_pool.py] Increasing active thread count to 9
[DEBUG    2011-01-03 11:29:40,833 adaptive_thread_pool.py] [WorkerThread-5] Got work item [151-160]
[DEBUG    2011-01-03 11:29:40,833 adaptive_thread_pool.py] [WorkerThread-1] Got work item [161-170]
[DEBUG    2011-01-03 11:29:40,902 bulkloader.py] [WorkerThread-6] [71-80] Transferred 10 entities in 0.6 seconds
[DEBUG    2011-01-03 11:29:40,903 adaptive_thread_pool.py] Increasing active thread count to 10
[DEBUG    2011-01-03 11:29:40,904 adaptive_thread_pool.py] [WorkerThread-6] Got work item [171-180]
[DEBUG    2011-01-03 11:29:40,904 adaptive_thread_pool.py] [WorkerThread-0] Got work item [181-190]
[DEBUG    2011-01-03 11:29:40,984 bulkloader.py] [WorkerThread-4] [91-100] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:40,984 adaptive_thread_pool.py] [WorkerThread-4] Got work item [191-200]
[DEBUG    2011-01-03 11:29:41,041 bulkloader.py] [WorkerThread-3] [101-110] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,041 adaptive_thread_pool.py] [WorkerThread-3] Got work item [201-210]
[DEBUG    2011-01-03 11:29:41,098 bulkloader.py] [WorkerThread-8] [111-120] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,098 adaptive_thread_pool.py] [WorkerThread-8] Got work item [211-220]
[DEBUG    2011-01-03 11:29:41,155 bulkloader.py] [WorkerThread-9] [131-140] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,157 adaptive_thread_pool.py] [WorkerThread-9] Got work item [221-230]
[DEBUG    2011-01-03 11:29:41,209 bulkloader.py] [WorkerThread-5] [151-160] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,210 adaptive_thread_pool.py] [WorkerThread-5] Got work item [231-240]
[DEBUG    2011-01-03 11:29:41,260 bulkloader.py] [WorkerThread-6] [171-180] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:41,260 adaptive_thread_pool.py] [WorkerThread-6] Got work item [241-250]
[DEBUG    2011-01-03 11:29:41,320 bulkloader.py] [WorkerThread-4] [191-200] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:41,321 adaptive_thread_pool.py] [WorkerThread-4] Got work item [251-260]
[DEBUG    2011-01-03 11:29:41,384 bulkloader.py] [WorkerThread-3] [201-210] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:41,384 adaptive_thread_pool.py] [WorkerThread-3] Got work item [261-270]
[DEBUG    2011-01-03 11:29:41,449 bulkloader.py] [WorkerThread-8] [211-220] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,449 adaptive_thread_pool.py] [WorkerThread-8] Got work item [271-280]
[DEBUG    2011-01-03 11:29:41,518 bulkloader.py] [WorkerThread-9] [221-230] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:41,518 adaptive_thread_pool.py] [WorkerThread-9] Got work item [281-290]
[DEBUG    2011-01-03 11:29:41,569 bulkloader.py] [WorkerThread-5] [231-240] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:41,569 adaptive_thread_pool.py] [WorkerThread-5] Got work item [291-300]
[DEBUG    2011-01-03 11:29:41,632 bulkloader.py] [WorkerThread-6] [241-250] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,632 adaptive_thread_pool.py] [WorkerThread-6] Got work item [301-310]
[DEBUG    2011-01-03 11:29:41,729 bulkloader.py] [WorkerThread-4] [251-260] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,730 adaptive_thread_pool.py] [WorkerThread-4] Got work item [311-320]
[DEBUG    2011-01-03 11:29:41,797 bulkloader.py] [WorkerThread-3] [261-270] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,798 adaptive_thread_pool.py] [WorkerThread-3] Got work item [321-330]
[ERROR    2011-01-03 11:29:41,849 bulkloader.py] Retrying on non-fatal URL error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 404, in Put
    return _GetConnection().async_put(config, entities, extra_hook).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 548, in get_result
    self.check_success()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 519, in check_success
    rpc.check_success()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 501, in check_success
    self.__rpc.CheckSuccess()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1173, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1148, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 54] Connection reset by peer>
[DEBUG    2011-01-03 11:29:41,851 bulkloader.py] [WorkerThread-8] [271-280] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,885 adaptive_thread_pool.py] [WorkerThread-8] Got work item [331-340]
[DEBUG    2011-01-03 11:29:41,925 bulkloader.py] [WorkerThread-9] [281-290] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,926 adaptive_thread_pool.py] [WorkerThread-9] Got work item [341-350]
[DEBUG    2011-01-03 11:29:41,930 adaptive_thread_pool.py] Decreasing the number of active threads to 9
[DEBUG    2011-01-03 11:29:41,991 bulkloader.py] [WorkerThread-5] [291-300] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:41,991 adaptive_thread_pool.py] Increasing active thread count to 10
[DEBUG    2011-01-03 11:29:41,991 adaptive_thread_pool.py] [WorkerThread-5] Got work item [181-190]
[DEBUG    2011-01-03 11:29:41,992 adaptive_thread_pool.py] [WorkerThread-0] Got work item [351-360]
[DEBUG    2011-01-03 11:29:42,061 bulkloader.py] [WorkerThread-7] [121-130] Transferred 10 entities in 1.3 seconds
[DEBUG    2011-01-03 11:29:42,061 adaptive_thread_pool.py] [WorkerThread-7] Got work item [361-370]
[DEBUG    2011-01-03 11:29:42,134 bulkloader.py] [WorkerThread-2] [141-150] Transferred 10 entities in 1.3 seconds
[DEBUG    2011-01-03 11:29:42,135 adaptive_thread_pool.py] [WorkerThread-2] Got work item [371-373]
[DEBUG    2011-01-03 11:29:42,168 bulkloader.py] [WorkerThread-4] [311-320] Transferred 10 entities in 0.4 seconds
[DEBUG    2011-01-03 11:29:42,225 bulkloader.py] [WorkerThread-8] [331-340] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:42,278 bulkloader.py] [WorkerThread-9] [341-350] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:42,339 bulkloader.py] [WorkerThread-5] [181-190] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:42,391 bulkloader.py] [WorkerThread-7] [361-370] Transferred 10 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:42,443 bulkloader.py] [WorkerThread-2] [371-373] Transferred 3 entities in 0.3 seconds
[DEBUG    2011-01-03 11:29:42,704 bulkloader.py] [WorkerThread-6] [301-310] Transferred 10 entities in 1.1 seconds
[ERROR    2011-01-03 11:29:42,750 bulkloader.py] Retrying on non-fatal URL error: [Errno 54] Connection reset by peer
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 691, in PerformWork
    transfer_time = self._TransferItem(thread_pool)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 848, in _TransferItem
    self.request_manager.PostEntities(self.content)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/bulkloader.py", line 1300, in PostEntities
    datastore.Put(entities)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/datastore.py", line 404, in Put
    return _GetConnection().async_put(config, entities, extra_hook).get_result()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 548, in get_result
    self.check_success()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/datastore/datastore_rpc.py", line 519, in check_success
    rpc.check_success()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 501, in check_success
    self.__rpc.CheckSuccess()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/apiproxy_rpc.py", line 149, in _WaitImpl
    self.request, self.response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 224, in MakeSyncCall
    handler(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 350, in _Dynamic_Put
    'datastore_v3', 'Put', put_request, put_response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 156, in MakeSyncCall
    self._MakeRealSyncCall(service, call, request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/remote_api/remote_api_stub.py", line 168, in _MakeRealSyncCall
    encoded_response = self._server.Send(self._path, encoded_request)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/appengine_rpc.py", line 341, in Send
    f = self.opener.open(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1173, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1148, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 54] Connection reset by peer>
[DEBUG    2011-01-03 11:29:42,783 adaptive_thread_pool.py] Decreasing the number of active threads to 9
[DEBUG    2011-01-03 11:29:42,784 adaptive_thread_pool.py] [WorkerThread-4] Got work item [161-170]
[DEBUG    2011-01-03 11:29:42,822 bulkloader.py] [WorkerThread-3] [321-330] Transferred 10 entities in 1.0 seconds
[DEBUG    2011-01-03 11:29:42,825 adaptive_thread_pool.py] Increasing active thread count to 10
[DEBUG    2011-01-03 11:29:42,873 bulkloader.py] [WorkerThread-4] [161-170] Transferred 10 entities in 0.1 seconds
[DEBUG    2011-01-03 11:29:43,001 bulkloader.py] [WorkerThread-0] [351-360] Transferred 10 entities in 1.0 seconds
[DEBUG    2011-01-03 11:29:43,011 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,011 adaptive_thread_pool.py] [WorkerThread-0] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,011 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,018 adaptive_thread_pool.py] [WorkerThread-6] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,039 adaptive_thread_pool.py] [WorkerThread-4] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,040 adaptive_thread_pool.py] [WorkerThread-1] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,040 adaptive_thread_pool.py] [WorkerThread-3] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,040 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,048 adaptive_thread_pool.py] [WorkerThread-8] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,049 adaptive_thread_pool.py] [WorkerThread-9] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,055 adaptive_thread_pool.py] [WorkerThread-5] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,056 adaptive_thread_pool.py] [WorkerThread-7] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,058 adaptive_thread_pool.py] [WorkerThread-2] WorkerThread: exiting
[DEBUG    2011-01-03 11:29:43,058 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 adaptive_thread_pool.py] Waiting for Anonymous_WorkerThread to exit
[DEBUG    2011-01-03 11:29:43,059 bulkloader.py] Waiting for progress_thread to terminate...
[DEBUG    2011-01-03 11:29:43,070 bulkloader.py] [Thread-13] ProgressTrackerThread: exiting
[DEBUG    2011-01-03 11:29:43,075 bulkloader.py] ... done.
[INFO     2011-01-03 11:29:43,075 bulkloader.py] 373 entites total, 0 previously transferred
[INFO     2011-01-03 11:29:43,075 bulkloader.py] 373 entities (87614 bytes) transferred in 7.5 seconds
[INFO     2011-01-03 11:29:43,075 bulkloader.py] All entities successfully transferred
